sudo: required
services:
    - docker

before_install:
    - docker build -t sirishkumar/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true sirishkumar/react-test npm test -- --coverage

after_success:
    - docker build -t sirishkumar/multi-client ./client
    - docker build -t sirishkumar/multi-nginx ./nginx 
    - docker build -t sirishkumar/multi-server ./server
    - docker build -t sirishkumar/multi-worker ./worker
    - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sirishkumar/multi-client
    - docker push sirishkumar/multi-nginx
    - docker push sirishkumar/multi-server
    - docker push sirishkumar/multi-worker

