sudo: required
services:
    - docker

before_install:
    - docker build -t sirishkumar/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true sirishkumar/react-test npm test -- --coverage

after_success:
    - docker build -t sirishkumar/multi-client ./client
    - docker build -t sirishkumar/multi-nginx ./nginx 
    - docker build -t sirishkumar/multi-server ./server
    - docker build -t sirishkumar/multi-worker ./worker
    - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sirishkumar/multi-client
    - docker push sirishkumar/multi-nginx
    - docker push sirishkumar/multi-server
    - docker push sirishkumar/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-537989015211
  bucket_path: docker-multi
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY


